Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -115,72 +115,72 @@ jobs:
         id: display_ip
         run: echo $(kubectl describe service flask-lb | grep Ingress | tr -d '/[a-zA-Z:]/g' | xargs);
 
-push-flask-to-prod:
-  runs-on: ubuntu-latest
-  needs:
-    - build-and-push
-    - flask-testing
-  steps:
-    - name: Configure AWS Credentials For GitHub Actions
-      uses: aws-actions/configure-aws-credentials@v2
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ env.AWS_REGION }}
-
-    - name: Write PEM file
-      uses: frdrwrt/write-to-file@v1.3
-      with:
-        filepath: hen.pem
-        content: ${{ secrets.AWS_SSH }}
-        mode: 744
-
-    - name: Start Prod Instance
-      id: start-instance
-      run: |
-        INSTANCE_ID=$(aws ec2 describe-instances \
-          --filters "Name=tag:Name,Values=hen prod" \
-          --query "Reservations[*].Instances[*].InstanceId" \
-          --output text)
-        
-        if [ -z "$INSTANCE_ID" ]; then
-          echo "No EC2 instance found with the name 'hen prod'."
-          exit 1
-        fi
-
-        echo "Starting EC2 instance with ID $INSTANCE_ID..."
-        aws ec2 start-instances --instance-ids $INSTANCE_ID
-        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
-
-        prodInstanceIP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].PublicIpAddress' --output text)
-        if [ -z "$prodInstanceIP" ]; then
-          echo "Failed to retrieve the public IP address of the instance."
-          exit 1
-        fi
-
-        echo "::set-output name=ip::$prodInstanceIP"
-      shell: bash
-      env:
-        AWS_REGION: eu-north-1
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-    - name: Clean Up Docker Images
-      run: |
-        echo "Cleaning up unused Docker images..."
-        sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "docker system prune -a --volumes -f"
-
-    - name: Pull Docker Image on EC2
-      run: |
-        echo "Pulling Docker image on EC2 prod server..."
-        sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "docker pull henhat583/flask-app:latest"
-
-    - name: Run Flask App on EC2 prod server
-      run: |
-        echo "Running Flask app on EC2 prod server..."
-        sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "sudo docker rm -f prod"
-        sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "sudo docker run -d -p 5000:5000 --name prod henhat583/flask-app:latest"
-
-    - name: Display URL
-      run: |
-        echo "The site is http://${{ steps.start-instance.outputs.ip }}:5000"
+  push-flask-to-prod:
+    runs-on: ubuntu-latest
+    needs:
+      - build-and-push
+      - flask-testing
+    steps:
+      - name: Configure AWS Credentials For GitHub Actions
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+  
+      - name: Write PEM file
+        uses: frdrwrt/write-to-file@v1.3
+        with:
+          filepath: hen.pem
+          content: ${{ secrets.AWS_SSH }}
+          mode: 744
+  
+      - name: Start Prod Instance
+        id: start-instance
+        run: |
+          INSTANCE_ID=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=hen prod" \
+            --query "Reservations[*].Instances[*].InstanceId" \
+            --output text)
+          
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "No EC2 instance found with the name 'hen prod'."
+            exit 1
+          fi
+  
+          echo "Starting EC2 instance with ID $INSTANCE_ID..."
+          aws ec2 start-instances --instance-ids $INSTANCE_ID
+          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
+  
+          prodInstanceIP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].PublicIpAddress' --output text)
+          if [ -z "$prodInstanceIP" ]; then
+            echo "Failed to retrieve the public IP address of the instance."
+            exit 1
+          fi
+  
+          echo "::set-output name=ip::$prodInstanceIP"
+        shell: bash
+        env:
+          AWS_REGION: eu-north-1
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  
+      - name: Clean Up Docker Images
+        run: |
+          echo "Cleaning up unused Docker images..."
+          sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "docker system prune -a --volumes -f"
+  
+      - name: Pull Docker Image on EC2
+        run: |
+          echo "Pulling Docker image on EC2 prod server..."
+          sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "docker pull henhat583/flask-app:latest"
+  
+      - name: Run Flask App on EC2 prod server
+        run: |
+          echo "Running Flask app on EC2 prod server..."
+          sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "sudo docker rm -f prod"
+          sudo ssh -i hen.pem -o StrictHostKeyChecking=no ec2-user@${{ steps.start-instance.outputs.ip }} "sudo docker run -d -p 5000:5000 --name prod henhat583/flask-app:latest"
+  
+      - name: Display URL
+        run: |
+          echo "The site is http://${{ steps.start-instance.outputs.ip }}:5000"
